Repository kcp-dev/api-syncagent, pull requests merged in 2025-02, with the labels that each got.

#15 ✨ Add workspace paths as annotations to synced objects
  deploy/crd/kcp.io/syncagent.kcp.io_publishedresources.yaml
  go.mod
  go.sum
  internal/controller/sync/controller.go
  internal/controller/syncmanager/lifecycle/cluster.go
  internal/sync/context.go
  internal/sync/context_test.go
  internal/sync/meta.go
  internal/sync/meta_test.go
  internal/sync/object_syncer.go
  internal/sync/state_store.go
  internal/sync/syncer.go
  internal/sync/syncer_test.go
  internal/sync/types.go
  sdk/apis/syncagent/v1alpha1/published_resource.go
  sdk/applyconfiguration/syncagent/v1alpha1/publishedresourcespec.go
Labels: release-note, size/L, approved, dco-signoff: yes, lgtm

#18 ✨ Label local objects with the agent name
  cmd/api-syncagent/main.go
  docs/getting-started.md
  internal/controller/sync/controller.go
  internal/controller/syncmanager/controller.go
  internal/sync/object_syncer.go
  internal/sync/syncer.go
  internal/sync/syncer_related.go
  internal/sync/syncer_test.go
  internal/sync/types.go
Labels: release-note, approved, size/M, dco-signoff: yes, lgtm

#19 ✨ Add basic support for mutating object contents during syncing
  deploy/crd/kcp.io/syncagent.kcp.io_publishedresources.yaml
  docs/publish-resources.md
  go.mod
  go.sum
  internal/controller/sync/controller.go
  internal/mutation/mutation.go
  internal/mutation/mutation_test.go
  internal/sync/syncer_related.go
  sdk/apis/syncagent/v1alpha1/published_resource.go
  sdk/apis/syncagent/v1alpha1/zz_generated.deepcopy.go
  sdk/applyconfiguration/syncagent/v1alpha1/publishedresourcespec.go
  sdk/applyconfiguration/syncagent/v1alpha1/relatedresourcespec.go
  sdk/applyconfiguration/syncagent/v1alpha1/resourcedeletemutation.go
  sdk/applyconfiguration/syncagent/v1alpha1/resourcemutation.go
  sdk/applyconfiguration/syncagent/v1alpha1/resourcemutationspec.go
  sdk/applyconfiguration/syncagent/v1alpha1/resourceregexmutation.go
  sdk/applyconfiguration/syncagent/v1alpha1/resourcetemplatemutation.go
  sdk/applyconfiguration/utils.go
Labels: release-note, approved, size/XL, dco-signoff: yes, lgtm

#21 🐛 drop all non-selected versions from CRDs when creating APIResourceSchemas
  internal/controller/apiresourceschema/controller.go
Labels: approved, size/S, dco-signoff: yes, lgtm, release-note-none

#22 ✨ Add end-to-end testing
  .gitignore
  .golangci.yml
  .prow.yaml
  Makefile
  go.mod
  hack/ci/run-e2e-tests.sh
  hack/ci/testdata/e2e-kcp.tokens
  hack/download-tool.sh
  hack/lib.sh
  hack/verify-boilerplate.sh
  test/crds/crontab.yaml
  test/e2e/apiresourceschema/apiresourceschema_test.go
  test/utils/fixtures.go
  test/utils/process.go
  test/utils/utils.go
  test/utils/wait.go
Labels: approved, size/XXL, dco-signoff: yes, lgtm, release-note-none

#24 🌱 Add integration tests for the apiexport controller
  cmd/api-syncagent/main.go
  cmd/api-syncagent/options.go
  docs/faq.md
  go.mod
  internal/controller/apiresourceschema/controller.go
  test/crds/backup.yaml
  test/crds/crontab-improved.yaml
  test/crds/crontab-multi-versions.yaml
  test/e2e/apiexport/apiexport_test.go
  test/e2e/apiresourceschema/apiresourceschema_test.go
  test/utils/fixtures.go
  test/utils/process.go
  test/utils/utils.go
Labels: release-note, approved, size/XL, dco-signoff: yes, lgtm

#28 🌱 Add first tests for the syncing logic
  hack/ci/run-e2e-tests.sh
  internal/controller/apiexport/controller.go
  internal/controller/sync/controller.go
  internal/sync/object_syncer.go
  test/e2e/sync/primary_test.go
  test/utils/process.go
  test/utils/wait.go
Labels: release-note, approved, size/XL, dco-signoff: yes, lgtm

#30 📖 (docs): fix the link
  docs/README.md
  docs/getting-started.md
Labels: ok-to-test, approved, dco-signoff: yes, size/XS, lgtm, release-note-none
