Repository kcp-dev/api-syncagent, pull requests merged in 2025-01, with the labels that each got.

#2 ✨ add prowjobs
  .golangci.yml
  .prow.yaml
  hack/ci/verify.sh
  hack/download-tool.sh
Labels: size/L, approved, dco-signoff: yes, lgtm, release-note-none

#3 :seedling: Add opencontainer labels to image
  Dockerfile
Labels: approved, dco-signoff: yes, size/XS, lgtm, release-note-none

#4 🐛 set labels on the final container image
  Dockerfile
Labels: approved, dco-signoff: yes, size/XS, lgtm, release-note-none

#6 :sparkles: Add kubeconfig-host-override and kubeconfig-ca-file-override flags
  cmd/api-syncagent/main.go
  cmd/api-syncagent/options.go
Labels: release-note, approved, size/S, dco-signoff: yes, lgtm

#8 🌱 Reword "platform" to "kcp"
  cmd/api-syncagent/main.go
  cmd/api-syncagent/options.go
  deploy/crd/kcp.io/syncagent.kcp.io_publishedresources.yaml
  docs/README.md
  docs/getting-started.md
  docs/publish-resources.md
  internal/controller/apiexport/controller.go
  internal/controller/apiexport/doc.go
  internal/controller/apiresourceschema/controller.go
  internal/controller/apiresourceschema/doc.go
  internal/controller/sync/doc.go
  internal/controller/syncmanager/controller.go
  internal/controller/syncmanager/doc.go
  internal/projection/projection.go
  internal/sync/syncer.go
  internal/sync/syncer_related.go
  sdk/apis/syncagent/v1alpha1/published_resource.go
Labels: release-note, size/L, approved, dco-signoff: yes, lgtm

#7 ⚠️ move object states Secrets to the namespace where the agent is running
  cmd/api-syncagent/main.go
  internal/controller/sync/controller.go
  internal/controller/syncmanager/controller.go
  internal/sync/state_store.go
  internal/sync/state_store_test.go
  internal/sync/syncer.go
  internal/sync/syncer_test.go
Labels: release-note, approved, size/M, dco-signoff: yes, lgtm

#10 :seedling: Update to Go 1.23.5 for builds and tests
  .prow.yaml
  Dockerfile
Labels: release-note, approved, size/S, dco-signoff: yes, lgtm

#14 📖 update documentation
  docs/README.md
  docs/consuming-services.md
  docs/faq.md
  docs/getting-started.md
Labels: size/L, approved, dco-signoff: yes, lgtm, release-note-none
