Repository kcp-dev/api-syncagent, pull requests merged in 2025-05, with the labels that each got.

#57 add support for multiversion docs
  .github/workflows/docs-gen-and-push.yaml
  .github/workflows/gh-pages.yaml
  Makefile
  Makefile.venv
  docs/.gitignore
  docs/scripts/deploy-docs.sh
  docs/scripts/serve-docs.sh
Labels: ok-to-test, approved, size/XL, dco-signoff: yes, lgtm, release-note-none, kind/documentation

#58 Update prow jobs to infra/build:1.23.7-2 image for ARM64 support
  .prow.yaml
Labels: kind/cleanup, approved, dco-signoff: yes, size/XS, lgtm, release-note-none

#63 pin Github actions in release workflow, update release pipeline to Go 1.23.7
  .github/workflows/release.yml
Labels: release-note, kind/cleanup, approved, size/S, dco-signoff: yes, lgtm

#62 Handle API lifecycle
  cmd/api-syncagent/main.go
  cmd/crd-puller/.gitignore
  cmd/crd-puller/README.md
  cmd/crd-puller/main.go
  deploy/crd/kcp.io/syncagent.kcp.io_publishedresources.yaml
  docs/content/api-lifecycle.md
  docs/content/faq.md
  docs/content/publish-resources.md
  docs/mkdocs.yml
  internal/controller/apiexport/controller.go
  internal/controller/apiexport/reconciler.go
  internal/controller/apiresourceschema/controller.go
  internal/controller/apiresourceschema/doc.go
  internal/controller/sync/controller.go
  internal/discovery/client.go
  internal/projection/projection.go
  internal/projection/projection_test.go
  internal/sync/syncer.go
  sdk/apis/syncagent/v1alpha1/published_resource.go
  sdk/apis/syncagent/v1alpha1/types.go
  sdk/apis/syncagent/v1alpha1/zz_generated.deepcopy.go
  sdk/applyconfiguration/syncagent/v1alpha1/resourceprojection.go
  sdk/applyconfiguration/syncagent/v1alpha1/sourceresourcedescriptor.go
  test/e2e/apiexport/apiexport_test.go
  test/e2e/apiresourceschema/apiresourceschema_test.go
  test/e2e/discovery/discovery_test.go
Labels: release-note, kind/feature, approved, size/XXL, dco-signoff: yes, lgtm

#64 update golangci-lint to 2.1.6
  .gimps.yaml
  .golangci.yml
  Makefile
  internal/discovery/client.go
Labels: kind/cleanup, size/L, approved, dco-signoff: yes, lgtm, release-note-none

#67 bump to Go 1.24.3
  .github/workflows/docs-gen-and-push.yaml
  .github/workflows/release.yml
  .prow.yaml
  Dockerfile
Labels: release-note, kind/feature, approved, size/S, dco-signoff: yes, lgtm

#66 Add support for Go template expressions in PublishedResources
  deploy/crd/kcp.io/syncagent.kcp.io_publishedresources.yaml
  docs/content/publish-resources/.pages
  docs/content/publish-resources/index.md
  docs/content/publish-resources/templating.md
  go.mod
  internal/projection/naming.go
  internal/projection/projection.go
  internal/sync/apis/dummy/v1alpha1/thing.go
  internal/sync/context_test.go
  internal/sync/crd/dummy.example.com_namespacedthings.yaml
  internal/sync/crd/dummy.example.com_things.yaml
  internal/sync/crd/dummy.example.com_thingwithstatuses.yaml
  internal/sync/crd/dummy.example.com_thingwithstatussubresources.yaml
  internal/sync/init_test.go
  internal/sync/object_syncer.go
  internal/sync/state_store_test.go
  internal/sync/syncer.go
  internal/sync/syncer_related.go
  internal/sync/syncer_related_test.go
  internal/sync/syncer_test.go
  internal/sync/templating/naming.go
  internal/sync/templating/naming_test.go
  internal/sync/templating/related.go
  internal/sync/templating/templating.go
  sdk/apis/syncagent/v1alpha1/published_resource.go
  sdk/applyconfiguration/syncagent/v1alpha1/relatedresourcespec.go
  test/e2e/apiexport/apiexport_test.go
  test/e2e/apiresourceschema/apiresourceschema_test.go
  test/e2e/discovery/discovery_test.go
  test/e2e/sync/primary_test.go
  test/e2e/sync/related_test.go
Labels: kind/feature, approved, size/XXL, dco-signoff: yes, release-note-action-required, lgtm
