Repository kcp-dev/api-syncagent, pull requests merged in 2025-04, with the labels that each got.

#49 🌱 update all dependencies, even indirect ones, to their latest versions
  go.mod
  go.sum
  hack/update-codegen-sdk.sh
Labels: approved, size/XL, dco-signoff: yes, lgtm, release-note-none

#50 :book: docs: add missing RBAC bindings / rules
  docs/getting-started.md
Labels: approved, size/S, dco-signoff: yes, needs-ok-to-test, lgtm, release-note-none

#51 :seedling: Remove emojis from PR template and verification
  .github/pull_request_template.md
  .github/workflows/pr-verifier.yaml
Labels: approved, size/M, dco-signoff: yes, lgtm, release-note-none

#54 docs: add workflow for publishing docs to gh-pages
  .github/workflows/gh-pages.yaml
  docs/content/publish-resources.md
Labels: ok-to-test, approved, size/M, dco-signoff: yes, lgtm, release-note-none, kind/documentation
