Repository kcp-dev/api-syncagent, pull requests merged in 2025-06, with the labels that each got.

#76 replace crd-puller with pubres-toolkit
  cmd/crd-puller/.gitignore
  cmd/crd-puller/README.md
  cmd/crd-puller/main.go
  cmd/pubres-toolkit/.gitignore
  cmd/pubres-toolkit/README.md
  cmd/pubres-toolkit/cmd/crd/command.go
  cmd/pubres-toolkit/cmd/crd/options.go
  cmd/pubres-toolkit/main.go
  cmd/pubres-toolkit/util/kubeconfig.go
  cmd/pubres-toolkit/util/pubres.go
  go.mod
  internal/controller/apiresourceschema/controller.go
  internal/kcp/apiresourceschema.go
Labels: release-note, kind/feature, approved, size/XL, dco-signoff: yes, lgtm

#79 fix typos
  .typos.toml
  docs/content/publish-resources/index.md
Labels: kind/cleanup, approved, size/S, dco-signoff: yes, lgtm, release-note-none

#80 fix example in label selector renaming
  docs/content/publish-resources/index.md
Labels: approved, dco-signoff: yes, size/XS, lgtm, release-note-none, kind/documentation

#81 Fix release branch naming scheme and badge links
  README.md
  docs/content/contributing/releasing.md
Labels: approved, dco-signoff: yes, size/XS, lgtm, release-note-none, kind/documentation

#82 Undeprecate references
  deploy/crd/kcp.io/syncagent.kcp.io_publishedresources.yaml
  internal/sync/syncer_related.go
  sdk/apis/syncagent/v1alpha1/published_resource.go
Labels: approved, size/M, dco-signoff: yes, lgtm, release-note-none, kind/documentation
