Repository kcp-dev/api-syncagent, pull requests merged in 2025-03, with the labels that each got.

#36 :sparkles: Add GoReleaser config and Release GitHub Action
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yaml
  Makefile
Labels: size/L, approved, dco-signoff: yes, lgtm, release-note-none

#29 ✨ Use OpenAPI schema to handle publishing non-CRD based resources
  cmd/crd-puller/README.md
  cmd/crd-puller/main.go
  go.mod
  go.sum
  internal/controller/apiresourceschema/controller.go
  internal/controller/sync/controller.go
  internal/controller/syncmanager/controller.go
  internal/discovery/client.go
  test/e2e/apiresourceschema/apiresourceschema_test.go
Labels: release-note, size/L, approved, dco-signoff: yes, lgtm

#39 🐛 prefer CRDs when discovery API types, as CRDs contain more betterer information
  internal/discovery/client.go
Labels: release-note, size/L, approved, dco-signoff: yes, lgtm

#40 🐛 Handle long object names
  internal/controller/apiresourceschema/controller.go
  internal/crypto/hash.go
  internal/projection/naming.go
  internal/sync/meta.go
  internal/sync/metadata.go
  internal/sync/object_syncer.go
  internal/sync/state_store.go
  internal/sync/syncer.go
  internal/sync/syncer_related.go
  internal/sync/syncer_test.go
  internal/sync/types.go
  test/e2e/sync/primary_test.go
Labels: release-note, approved, size/XL, dco-signoff: yes, lgtm

#42 🐛 Fix labels on related resources, fix syncing related resources, add first e2e test
  internal/controller/syncmanager/lifecycle/cluster.go
  internal/sync/metadata.go
  internal/sync/object_syncer.go
  test/e2e/sync/related_test.go
Labels: release-note, size/L, approved, dco-signoff: yes, lgtm
